<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class bit24 extends \ccxt\Exchange {
    public function public_get_api_external_tokenbaz_cryptocurrency_pricing($params = array()) {
        return $this->request('api/external/tokenbaz/cryptocurrency-pricing', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetApiExternalTokenbazCryptocurrencyPricing($params = array()) {
        return $this->request('api/external/tokenbaz/cryptocurrency-pricing', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
}
